// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBbMw8O_VOlYtZkCaLzLNR3IH5hYJ_tkd0',
    appId: '1:707461754785:web:87997b277f5e96d43ee5e0',
    messagingSenderId: '707461754785',
    projectId: 'namaz-152fb',
    authDomain: 'namaz-152fb.firebaseapp.com',
    storageBucket: 'namaz-152fb.appspot.com',
    measurementId: 'G-K3D2B5L2CB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBJel2G_Old6bWoHQjwyBQPQe4rS6PSrio',
    appId: '1:707461754785:android:261527e3e575dc103ee5e0',
    messagingSenderId: '707461754785',
    projectId: 'namaz-152fb',
    storageBucket: 'namaz-152fb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAQIvvtshBGjU2mkxquf81NFjmXG-2cNug',
    appId: '1:707461754785:ios:04143fcf12d3857b3ee5e0',
    messagingSenderId: '707461754785',
    projectId: 'namaz-152fb',
    storageBucket: 'namaz-152fb.appspot.com',
    iosClientId: '707461754785-lfe616u0ji12b61jrb40jj6pjn9eqa1o.apps.googleusercontent.com',
    iosBundleId: 'com.example.namazReminders',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAQIvvtshBGjU2mkxquf81NFjmXG-2cNug',
    appId: '1:707461754785:ios:04143fcf12d3857b3ee5e0',
    messagingSenderId: '707461754785',
    projectId: 'namaz-152fb',
    storageBucket: 'namaz-152fb.appspot.com',
    iosClientId: '707461754785-lfe616u0ji12b61jrb40jj6pjn9eqa1o.apps.googleusercontent.com',
    iosBundleId: 'com.example.namazReminders',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBbMw8O_VOlYtZkCaLzLNR3IH5hYJ_tkd0',
    appId: '1:707461754785:web:5bd14eb7a26846933ee5e0',
    messagingSenderId: '707461754785',
    projectId: 'namaz-152fb',
    authDomain: 'namaz-152fb.firebaseapp.com',
    storageBucket: 'namaz-152fb.appspot.com',
    measurementId: 'G-1JPR517RQH',
  );
}
